### PR TITLE
Add purdue recipes

### PR DESCRIPTION
**Pull request by dstoup**
This branch adds the recipes for packages to support the Purdue code base. There are some issues with the Purdue repo itself which need to be resolved before they can go in.

### CODE REVIEW

**Comment by dstoup** [comment]
@danlipsa

**Comment by danlipsa** [comment]
@dstoup I see that the purdue code is provided as a tgz instead of a link to the gitlab repo. Is that what you are referring too? What is the problem?

**Comment by danlipsa** [comment]
Did you have to add the CMakeLists.txt yourself?

**Comment by dstoup** [comment]
I didn't upload the Purdue code yet because of that. I made them tarballs because I was having some trouble with using the gitlab repo. Some of it was a result of building the recipe in the docker container and not having access to the repo, since code isnt' public. The other issue was the directory layout being non-traditional. I think I figured that issue out though and could just point to a different source directory.

I have a branch on the Purdue repository which adds the CMakeLists.txt to Reconstruction and fixes a handful of issues that prevent it from compiling. That code is in a MR, 

https://gitlab.kitware.com/core3d/core3d-purdue/merge_requests/2

**Comment by danlipsa** [comment]
Super-seeded by https://github.com/OpenDataAnalytics/kitware-geospatial-recipes/pull/28

**Pull request closed without merging**
